default:
  before_script:
    - echo "$CI_JOB_TOKEN" | docker login -u "$CI_REGISTRY_USER" --password-stdin $CI_REGISTRY

stages:
  - build
  - cleanup
  - deploy_prod
  - deploy_dev

variables:
  VITE_APP_IMAGE_NAME: $CI_REGISTRY_IMAGE/vite-app/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHA

build:
  stage: build
  script:
    - curl -s -X POST https://api.telegram.org/bot$BOT_TOKEN/sendMessage -d chat_id=$CHAT_BOT_ID -d text="🔨New Pholend Build Started%0A👨‍💻$GITLAB_USER_NAME"
    - docker build . -t $VITE_APP_IMAGE_NAME
    - docker push $VITE_APP_IMAGE_NAME
  tags:
    - lumos

cleanup:
  stage: cleanup
  when: always
  script:
    - docker system prune -f || true
  tags:
    - lumos

deploy_prod:
  stage: deploy_prod
  script:
    - curl -s -X POST https://api.telegram.org/bot$BOT_TOKEN/sendMessage -d chat_id=$CHAT_BOT_ID -d text="🤞Prod Pholend Deploy Started%0A👨‍💻$GITLAB_USER_NAME"
    - git config user.email cicd@lumos.com
    - git config user.name "cicd-lumos"
    - git clone ssh://git@git.dapp-devs.com:2222/lumos-labs/lumos-infra.git lumos-infra
    - cd lumos-infra
    - (cd ioc-helm; IMAGE_TAG=$CI_COMMIT_SHA yq e '.image.tag=env(IMAGE_TAG)' -i pholend/values.yaml)
    - git add .
    - git commit -m "updated Pholend"
    - git push origin
    - curl -s -X POST https://api.telegram.org/bot$NOTIFY_TOKEN/sendMessage -d chat_id=$CHAT_NOTIFY_ID -d text="🌈Prod Pholend Deploy Finished, wait for a sync in ArgoCD%0A👨‍💻$GITLAB_USER_NAME"
  tags:
    - lumos
  only:
    - main

deploy_dev:
  stage: deploy_dev
  script:
    - curl -s -X POST https://api.telegram.org/bot$BOT_TOKEN/sendMessage -d chat_id=$CHAT_BOT_ID -d text="🤞Dev Pholend Deploy Started%0A👨‍💻$GITLAB_USER_NAME"
    - git config user.email cicd@lumos.com
    - git config user.name "cicd-lumos"
    - git clone ssh://git@git.dapp-devs.com:2222/lumos-labs/lumos-infra.git lumos-infra
    - cd lumos-infra
    - (cd ioc-helm; IMAGE_TAG=$CI_COMMIT_SHA yq e '.image.tag=env(IMAGE_TAG)' -i pholend/dev.yaml)
    - git add .
    - git commit -m "updated Pholend"
    - git push origin
    - curl -s -X POST https://api.telegram.org/bot$NOTIFY_TOKEN/sendMessage -d chat_id=$CHAT_NOTIFY_ID -d text="🌈Dev Pholend Deploy Finished, wait for a sync in ArgoCD%0A👨‍💻$GITLAB_USER_NAME"
  tags:
    - lumos
  only:
    - dev
