/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: "",
  theme: {
    fontFamily: {
      arial: ["Arial", "sans-serif"],
    },
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        'main': 'var(--main)',
        'logo': 'var(--logo)',
        'white': 'var(--white)',
        'bg': 'var(--bg)',
        'button-40': 'var(--button-40)',
        'stroke': 'var(--stroke)',
        'stroke-60': 'var(--stroke-60)',
        'text': 'var(--text)',
        'text-white': 'var(--text-white)',
        'text-100': 'var(--text-100)',
        'text-90': 'var(--text-90)',
        'text-80': 'var(--text-80)',
        'error': 'var(--error)',
        'error-card-40': 'var(--error-card-40)',
        'violet-text': 'var(--violet-violet-text)',
        'violet-100': 'var(--violet-100)',
        'violet-40': 'var(--violet-40)',
        'violet-15': 'var(--violet-15)',
        'violet-4': 'var(--violet-4)',
        'blue1': 'var(--blue-blue1)',
        'blue2': 'var(--blue-blue2)',
        'green-100': 'var(--green-100)',
        'green-50': 'var(--green-50)',
        'green-10': 'var(--green-10)',
        'gray-gray-100': 'var(--gray-gray-100)',
        'gray-70': 'var(--gray-70)',
        'gray-50': 'var(--gray-50)',
        'dark-bg': 'var(--dark-bg)',
        'dark-cards-100': 'var(--dark-cards-100)',
        'dark-cards-70': 'var(--dark-cards-70)',
        'dark-default-input-4': 'var(--dark-default-input-4)',
        'dark-some-button': 'var(--dark-some-button)',
        'mobile-dark-bg': 'var(--mobile-dark-bg)',
        'mobile-dark-white': 'var(--mobile-dark-white)',
        'mobile-dark-green': 'var(--mobile-dark-green)',
        'mobile-dark-blue-1': 'var(--mobile-dark-blue-1)',
        'mobile-dark-blue-20': 'var(--mobile-dark-blue-20)',
        'mobile-dark-blue-2': 'var(--mobile-dark-blue-2)',
        'mobile-dark-gray-text': 'var(--mobile-dark-gray-text)',
        'mobile-dark-gray-70-bg-card': 'var(--mobile-dark-gray-70-bg-card)',
        'mobile-dark-violet-100': 'var(--mobile-dark-violet-100)',
        'mobile-dark-violet-15': 'var(--mobile-dark-violet-15)',
        'mobile-dark-violet-4': 'var(--mobile-dark-violet-4)',
      },
      boxShadow: {
        'shadow': 'var(--shadow)',
        'dark-shadow': 'var(--dark-shadow)',
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
}